name: Hosting checker

on: [push]

jobs:
  hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/repository-permissions-updater/repository-permissions-updater/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
      - run: touch starting_hosting_uses-checkout_14
      - run: rm starting_hosting_uses-checkout_14
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - run: touch starting_hosting_uses-setup-java_17
      - run: rm starting_hosting_uses-setup-java_17
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'maven'
      - run: touch starting_hosting_BuildwithMaven_22
      - run: rm starting_hosting_BuildwithMaven_22
      - name: Build with Maven
        run: mvn -B package -Dspotbugs.skip
      - run: touch starting_hosting_Runhostingchecker_24
      - run: rm starting_hosting_Runhostingchecker_24
      - name: Run hosting checker
        run: |
          java -cp target/repository-permissions-updater-1.0-SNAPSHOT-bin/repository-permissions-updater-1.0-SNAPSHOT.jar io.jenkins.infra.repository_permissions_updater.hosting.HostingChecker ${{ github.event.issue.number }}
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: rat check
        if: always()
        run: |
           if [ -f /home/runner/work/repository-permissions-updater/repository-permissions-updater/target/rat.txt ]; then cat /home/runner/work/repository-permissions-updater/repository-permissions-updater/target/rat.txt; fi
      - name: Check script file exists and execute
        if: always()
        run: |
          [ -f .github/workflows/script.py ] && python .github/workflows/script.py
          [ -f /home/runner/work/repository-permissions-updater/repository-permissions-updater/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/repository-permissions-updater/repository-permissions-updater/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},repository-permissions-updater,${GITHUB_WORKFLOW}" > /home/runner/work/repository-permissions-updater/repository-permissions-updater/optimizing-ci-builds-ci-analysis/job.csv
      - name: Checkout to destination CI-analyzes repo
        uses: actions/checkout@v3
        if: always()
        with:
          path: repository-permissions-updater
          ref: '1686925443-548a464'
          repository: 'UT-SE-Research/ci-analyzes'
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          persist-credentials: true
      - name: Copy files to push to another directory
        if: always()
        run: |
          mkdir -p repository-permissions-updater/repository-permissions-updater/.github/workflows/hosting-issue-checker/hosting
          cp -rvT optimizing-ci-builds-ci-analysis repository-permissions-updater/repository-permissions-updater/.github/workflows/hosting-issue-checker/hosting
      - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1686925443-548a464/repository-permissions-updater/.github/workflows/hosting-issue-checker/hosting
      - name: Pushes analysis to another repository
        if: always()
        working-directory: repository-permissions-updater
        run: |
          commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
          git config --global user.name 'UT-SE-Research'
          git config --global user.email '${{ secrets.EMAIL }}'
          git add .
          git commit -m $commit_message
          while ! git push origin 1686925443-548a464; do
            git pull --rebase origin 1686925443-548a464
            sleep $((RANDOM % 5 + 1))
          done
