name: Hosting re-checker

on: [push]

jobs:
  hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/repository-permissions-updater/repository-permissions-updater/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - run: touch starting_hosting_Ack_14
      - run: rm starting_hosting_Ack_14
      - name: Ack
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });
      - run: touch starting_hosting_uses-checkout_25
      - run: rm starting_hosting_uses-checkout_25
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - run: touch starting_hosting_uses-setup-java_28
      - run: rm starting_hosting_uses-setup-java_28
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'maven'
      - run: touch starting_hosting_BuildwithMaven_33
      - run: rm starting_hosting_BuildwithMaven_33
      - name: Build with Maven
        run: mvn -B package -Dspotbugs.skip
      - run: touch starting_hosting_Runhostingchecker_35
      - run: rm starting_hosting_Runhostingchecker_35
      - name: Run hosting checker
        run: |
          java -cp target/repository-permissions-updater-1.0-SNAPSHOT-bin/repository-permissions-updater-1.0-SNAPSHOT.jar io.jenkins.infra.repository_permissions_updater.hosting.HostingChecker ${{ github.event.issue.number }}
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676524343-c797686'
          target-directory: 'repository-permissions-updater/.github/workflows/hosting-comment-checker/hosting'
        continue-on-error: true
      - name: Check push directory exit code
        if: steps.push_directory.outcome == 'failure'
        run: |
          echo 'push failed, trying pull and then push'
          git fetch
          git merge origin/1676524343-c797686
          while ! git push origin {time}; do
            git fetch
            git merge origin/1676524343-c797686
          done
