name: Hosting hoster
'on':
  issue_comment:
    types:
    - created
    - edited
jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/hosting host' }}
    outputs:
      actor_in_hosting_team: ${{ steps.checkUserMember.outputs.isTeamMember }}
    steps:
    - name: Ack
      uses: actions/github-script@v4
      with:
        script: "const {owner, repo} = context.issue\ngithub.reactions.createForIssueComment({\n\
          \  owner,\n  repo,\n  comment_id: context.payload.comment.id,\n  content:\
          \ \"+1\",\n});\n"
    - uses: tspascoal/get-user-teams-membership@v1
      id: checkUserMember
      with:
        username: ${{ github.actor }}
        team: hosting
        GITHUB_TOKEN: ${{ secrets.HOSTING_PAT }}
