name: Hosting hoster
'on':
  issue_comment:
    types:
    - created
    - edited
jobs:
  hosting:
    runs-on: ubuntu-latest
    needs:
    - validate
    if: needs.validate.outputs.actor_in_hosting_team == 'true'
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dspotbugs.skip
    - name: Run hoster
      run: 'java -cp target/repository-permissions-updater-1.0-SNAPSHOT-bin/repository-permissions-updater-1.0-SNAPSHOT.jar
        io.jenkins.infra.repository_permissions_updater.hosting.Hoster ${{ github.event.issue.number
        }}

        '
      env:
        GITHUB_OAUTH: ${{ secrets.HOSTING_PAT }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
